import React from 'react';
export function HelpModal({ isOpen, onClose }) {
  if (!isOpen) return null;
  return <div style={s.overlay} onClick={onClose}><div style={s.modal} onClick={(e)=>e.stopPropagation()}><div style={s.head}><div><h2 style={{margin:0}}>Как работать с DETI_INDIGO</h2><div style={s.sub}>Короткая памятка по основному сценарию</div></div><button style={s.close} onClick={onClose}>×</button></div><div style={s.grid}>
    <Step n="1" title="Создай проект" text="Укажи название и сроки проекта."/><Step n="2" title="Добавь задачи" text="Задай даты, статус, прогресс, ответственного и зависимости."/><Step n="3" title="Следи за планом" text="Используй таблицу и диаграмму Ганта. Полосы на Ганте можно двигать."/><Step n="4" title="Проверяй риски" text="Смотри просрочки, критический путь, дедлайны и загрузку команды."/><Step n="5" title="Используй AI" text="Спроси ассистента о рисках, приоритетах и состоянии текущего проекта."/><Step n="6" title="Выгрузи результат" text="Экспортируй задачи в CSV или распечатай сводный отчёт в PDF."/>
  </div></div></div>;
}
function Step({n,title,text}){return <div style={s.step}><span style={s.num}>{n}</span><div><strong>{title}</strong><div style={s.text}>{text}</div></div></div>}
const s={overlay:{position:'fixed',inset:0,background:'rgba(15,23,42,.58)',backdropFilter:'blur(4px)',display:'flex',alignItems:'center',justifyContent:'center',padding:18,zIndex:1200},modal:{width:'100%',maxWidth:720,background:'#fff',borderRadius:20,padding:24,boxShadow:'0 24px 80px rgba(15,23,42,.24)'},head:{display:'flex',justifyContent:'space-between',gap:16,marginBottom:18},sub:{fontSize:12,color:'#64748b',marginTop:5},close:{border:0,background:'#f1f5f9',width:34,height:34,borderRadius:10,fontSize:24,cursor:'pointer'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10},step:{display:'flex',gap:10,padding:12,border:'1px solid #e2e8f0',borderRadius:12,background:'#f8fafc'},num:{display:'grid',placeItems:'center',flex:'0 0 28px',height:28,borderRadius:9,background:'#eef2ff',color:'#4338ca',fontWeight:900},text:{fontSize:12,color:'#64748b',lineHeight:1.45,marginTop:4}};
